### 공통 환경 설정
spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: true
---
### local 환경 설정
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./local_db;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true
---
### prod 환경 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./prod_db;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update